server:
  port: ${sp.payablemanagement}
spring:
  application:
    name: ${sn.payablemanagement}
  datasource:
    url: jdbc:mysql://localhost:3306/payable_management?serverTimezone=UTC&characterEncoding=utf8&useUnicode=ture&useSSL=false
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    name: druid
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）